version = 1

test_patterns = ["**/*_test.*"]

exclude_patterns = ["src/components/ui/*"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["vitest"]