version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/omar-kada/autonas"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"