version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/omar-kada/autonas:backend"

[[analyzers]]
name = "test-coverage"
enabled = true

[[code_formatters]]
name = "gofmt"
exclude_patterns = ["**/api/api/gen.go"]

[[code_formatters]]
name = "gofumpt"
exclude_patterns = ["**/api/api/gen.go"]
