openapi: 3.1.0
info:
  title: AutoNAS API
  version: '1.0'
tags:
  - name: Deployment
  - name: Status
paths:
  /api/deployment:
    get:
      operationId: DeployementAPI_list
      description: List widgets
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deployment'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Deployment
  /api/deployment/{id}:
    get:
      operationId: DeployementAPI_read
      description: Read widgets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Deployment
  /api/status:
    get:
      operationId: StatusAPI_get
      description: List widgets
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StackStatus'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Status
components:
  schemas:
    AnalyzeResult:
      type: object
      required:
        - id
        - analysis
      properties:
        id:
          type: string
        analysis:
          type: string
    ContainerStatus:
      type: object
      required:
        - containerId
        - state
        - name
        - health
        - createdAt
      properties:
        containerId:
          type: string
        state:
          type: string
          enum:
            - created
            - running
            - paused
            - restarting
            - removing
            - exited
            - dead
        name:
          type: string
        health:
          type: string
          enum:
            - healthy
            - unhealthy
            - starting
            - none
        createdAt:
          type: string
          format: date-time
    Deployment:
      type: object
      required:
        - id
        - title
        - time
        - diff
        - status
        - logs
      properties:
        id:
          type: string
        title:
          type: string
        time:
          type: string
          format: date-time
        diff:
          type: string
        status:
          type: string
          enum:
            - planned
            - running
            - success
            - error
        logs:
          type: array
          items:
            type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    StackStatus:
      type: object
      required:
        - stackId
        - name
        - services
      properties:
        stackId:
          type: string
        name:
          type: string
        services:
          type: array
          items:
            $ref: '#/components/schemas/ContainerStatus'
    Versions:
      type: string
      enum:
        - '1.0'
